language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - npm install
  - gatsby build
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
